name: Create Config in another repository

on:
  push:
    branches:
      - main

jobs:
  create-config:
    uses: flurdy/test-action-launchee/.github/workflows/create-config-trigger.yml@main
    with:
      repositoryName: some-repo # ${{ env.REPOSITORY_NAME }}
