name: Create Config in another repository

on:
  push:
    branches:
      - main

jobs:
  create-config:
    uses: flurdy/tests-action-launchee/.github/workflows/create-config-trigger.yml@main
    with:
      repositoryName: ${{ env.REPOSITORY_NAME }}
